[package]
name = "svf_filter"
version = "0.1.0"
authors = ["Fredemus <frederik.halkjaer1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "svf_gui"
crate-type = ["cdylib"]
[dependencies]
vst = { git = "https://github.com/rust-dsp/rust-vst" }
baseview = {git = "https://github.com/RustAudio/baseview", branch = "master"}
imgui-baseview = {git = "https://github.com/BillyDM/imgui-baseview", branch = "main"}
imgui = "0.7"
imgui-knobs = {git = "https://github.com/DGriffin91/imgui-rs-knobs", branch = "main"}
raw-window-handle = "0.3"
