[package]
name = "svf_filter"
version = "0.1.0"
authors = ["Fredemus <frederik.halkjaer1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vst = { git = "https://github.com/rust-dsp/rust-vst" }

[lib]
name = "svf_model"
crate-type = ["cdylib"]